resource_group_name     = "RG_Azure"
resource_group_location = "eastus"
app_service_plan_name   = "api-appserviceplan-pro"
azurevm_name            =  "azurerm_linux_virtual_machine"
azurevn_name            =  "azurerm_virtual_network"
azure_nic_name          =  "azurerm_network_interface"
